# Generated by Django 4.2.6 on 2024-07-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ')], max_length=10)),
                ('date_of_bitrh', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=100)),
                ('year_of_enrollment', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Đang học'), ('Graduated', 'Đã tốt nghiệp'), ('Suspended', 'Bị đình chỉ')], max_length=20)),
            ],
        ),
    ]
